version: '3'
services:
  api:
    container_name: esppm_api
    image: avadeu/esppm:0.8
    restart: on-failure
    ports:
      - "4200:4200"
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: esppm_db
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
        - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'